#ifndef RETRIEVEMISTAKE_INCORRECTSQUAREOFDIFBINOMIALMISTAKE_H
#define RETRIEVEMISTAKE_INCORRECTSQUAREOFDIFBINOMIALMISTAKE_H


#include "Mistake.h"

class IncorrectSquareOfDifBinomialMistake : public Mistake {

};


#endif //RETRIEVEMISTAKE_INCORRECTSQUAREOFDIFBINOMIALMISTAKE_H
